# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/playfair.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import os
# Chỉ đường để Python thấy thư mục cha
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
# Import chính xác tên Class từ file
from playfair.playfair_cipher import PlayFairCipher

import os
os.environ['QT_QPA_PLANTFORM_PLUGIN_PATH'] = "../plantforms"
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(486, 365)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 0, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 80, 47, 13))
        self.label_2.setObjectName("label_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(120, 70, 261, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 120, 47, 13))
        self.label_3.setObjectName("label_3")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(120, 110, 261, 71))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(120, 280, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 280, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 210, 47, 13))
        self.label_4.setObjectName("label_4")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(120, 190, 261, 71))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 486, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "PlayFair Cipher"))
        self.label_2.setText(_translate("MainWindow", "Key:"))
        self.label_3.setText(_translate("MainWindow", "Mã Hoá:"))
        self.pushButton.setText(_translate("MainWindow", "Mã Hoá"))
        self.pushButton_2.setText(_translate("MainWindow", "Giải Mã"))
        self.label_4.setText(_translate("MainWindow", "Giải mã:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    def thuc_hien_ma_hoa(self):
        # Lấy dữ liệu từ giao diện
        key = self.plainTextEdit.toPlainText()
        van_ban_goc = self.plainTextEdit_2.toPlainText()

        # Gọi thuật toán và in ra kết quả
        if key and van_ban_goc:
            cipher = PlayFairCipher()
            ket_qua = cipher.encrypt(van_ban_goc, key) 
            # In kết quả mã hoá xuống ô thứ 3
            self.plainTextEdit_3.setPlainText(ket_qua)

    def thuc_hien_giai_ma(self):
        # Lấy dữ liệu từ giao diện
        key = self.plainTextEdit.toPlainText()
        van_ban_ma = self.plainTextEdit_3.toPlainText()

        # Gọi thuật toán và in ra kết quả
        if key and van_ban_ma:
            cipher = PlayFairCipher()
            ket_qua = cipher.decrypt(van_ban_ma, key)
            # In kết quả giải mã ngược lên ô thứ 2
            self.plainTextEdit_2.setPlainText(ket_qua)
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
